pipeline {
  agent {
                label "slave"
            }
  stages {
    stage('git-stage') {
      steps {
        sh '''
        rm -rf *
          git --version
          git clone 'https://github.com/shafiunpat/bismilla.git'
          git --version
        '''
      }
    }
    stage('maven-stage') {
      steps {
        sh '''
        mvn --version
        ls -lart
          cd bismilla
          cd Devopsjava
          cd demo
          mvn clean install 
        '''
      }
    }
     stage('docker-stage') {
      steps {
        agent {
                label "slave"
            }
        sh '''
        cd bismilla/Devopsjava
        docker --version
        docker build -t "bissmilla-${env.BUILD_ID}" . 
        docker run -itd --name bissmilla-${env.BUILD_ID} -p 8080:8080 -p 50000:50000 bissmilla-${env.BUILD_ID}  
        '''
      }
    }
  }
}
