pipeline {
  agent {
                label "slave"
            }
  stages {
    stage('git-stage') {
      steps {
        sh '''
        rm -rf *
          git --version
          git clone 'https://github.com/shafiunpat/bismilla.git'
          git --version
        '''
      }
    }
    stage('maven-stage') {
      steps {
        sh '''
        mvn --version
        ls -lart
          cd bismilla
          cd Devopsjava
          cd demo
          mvn clean install 
        '''
      }
    }
     stage('docker-stage') {
      steps {
        agent {
                label "slave"
            }
        sh '''
        cd bismilla/Devopsjava/demo
        ls -lart
        docker --version
        ls -lart
        docker build -t "bissmilla" .
        '''
      }
    }
  }
}
